[package]
name = "smem"
version = "0.1.0"
authors = ["Alex Muscar", "Laurențiu Nicola <lnicola@dend.ro>"]
edition = "2018"

[dependencies]
humansize = "1.1"
rayon = "1.3"
libc = "0.2"
regex = "1.3"
structopt = "0.3"
users = "0.9"
