[package]
name = "smem"
version = "0.1.0"
authors = ["Alex Muscar", "Laurențiu Nicola <lnicola@dend.ro>"]
edition = "2018"

[dependencies]
humansize = "1.1"
libc = "0.2"
rayon = "1.1"
regex = "1.2"
structopt = "0.2"
users = "0.9"
