[package]
name = "smem"
version = "0.1.0"
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
edition = "2018"

[dependencies]
humansize = "1.1"
rayon = "1.0"
regex = "1.0"
structopt = "0.2"
users = "0.8"
